# programming language specific aliases

# rust
- name: cgc
  value: cargo clippy --all-targets --all-features -- -D warnings
- name: cgt
  value: cargo test --all

# python
- name: py
  value: uv run
- name: pyc
  value: find . -name '*.pyc' -delete
  type: function
- name: pyv
  value: uv venv
- name: pyf
  value: ruff format
- name: pyl
  value: ruff check
