# ------------------------------------------------------------------------- #
# lazygit config                                                            #
# docs: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md #
# ------------------------------------------------------------------------- #

gui:
  expandFocusedSidePanel: true
